
SOURCES += \
    ../jkmathparser.cpp \
    ../jkmpdefaultlib.cpp \
    ../jkmptools.cpp \
    ../jkmpbase.cpp \
    ../jkmpstringtools.cpp \
    ../jkmpmathtools.cpp \
    ../jkmpfilenametools.cpp \
    ../StatisticsTools/correlator_multitau.cc \
    ../StatisticsTools/statistics_tools.cpp \
    highrestimer.cpp

HEADERS += \
    ../jkmathparser.h \
    ../jkmpbase.h \
    ../jkmpdefaultlib.h \
    ../jkmplib_imexport.h \
    ../jkmptools.h \
    ../jkmpstringtools.h \
    ../jkmpmathtools.h \
    ../jkmpfilenametools.h \
    ../extlibs/MersenneTwister.h \
    ../StatisticsTools/correlator.h \
    ../StatisticsTools/correlator_block.h \
    ../StatisticsTools/correlator_lag.h \
    ../StatisticsTools/correlator_multitau.h \
    ../StatisticsTools/lib_imexport.h \
    ../StatisticsTools/multitau-correlator.h \
    ../StatisticsTools/multitau-msd.h \
    ../StatisticsTools/shiftregister.h \
    ../StatisticsTools/statistics_tools.h \
    tictoc.h \
    highrestimer.h \
    ticktock.h

